name: Prevent Cold Starts

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (UTC time)
  workflow_dispatch:  

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          curl --silent https://wordcloud-31n0.onrender.com/form
          curl --silent https://wordcloud-31n0.onrender.com/cloud
